# -*- coding: utf-8 -*-
"""إنشاء سكربتات Python لإرسالها إلى Codex"""

import time
import socket
import platform


def generate_codex_script(user_request, target_system):
    """توليد سكربت Python متكامل لإرساله إلى Codex"""
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    safe_request = user_request.replace('"""', '\\"\\"\\"')
    
    script = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CodeX Task Request - Generated by WiFi Guardian Toolkit
   Time: {timestamp}
   System: {target_system}
"""

import os
import sys
import subprocess
import json
import socket
import platform
from datetime import datetime

USER_REQUEST = \"\"\"{safe_request}\"\"\"
TARGET_SYSTEM = "{target_system}"

REQUEST_INFO = {{
    "timestamp": "{timestamp}",
    "requester": "WiFi Guardian Toolkit",
    "request": USER_REQUEST[:200],
    "target_system": TARGET_SYSTEM,
    "hostname": socket.gethostname(),
    "platform": platform.system(),
    "python_version": sys.version
}}

def log_message(message, level="INFO"):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{{timestamp}}] [{{level}}] {{message}}")

def execute_command(command, shell=True):
    try:
        result = subprocess.run(
            command if isinstance(command, list) else command,
            capture_output=True,
            text=True,
            shell=shell,
            timeout=30
        )
        return {{
            "success": result.returncode == 0,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode
        }}
    except subprocess.TimeoutExpired:
        return {{"success": False, "error": "Timeout (30s)"}}
    except Exception as e:
        return {{"success": False, "error": str(e)}}

def analyze_request():
    log_message(f"Analyzing: {{USER_REQUEST[:100]}}...")
    request_lower = USER_REQUEST.lower()
    
    if any(w in request_lower for w in ["ip", "عنوان", "address"]):
        return handle_ip_request()
    elif any(w in request_lower for w in ["ويفاي", "wifi", "شبكة", "network"]):
        return handle_network_request()
    elif any(w in request_lower for w in ["dns", "دي ان اس"]):
        return handle_dns_request()
    elif any(w in request_lower for w in ["ping", "بنق", "اتصال"]):
        return handle_ping_request()
    elif any(w in request_lower for w in ["open", "فتح", "launch"]):
        return handle_open_request()
    else:
        return handle_general_request()

def handle_ip_request():
    results = {{}}
    if TARGET_SYSTEM in ["kali-linux windows", "kali-linux", "wsl"]:
        results["hostname_ip"] = execute_command("hostname -I").get("stdout", "").strip()
        results["ip_addr"] = execute_command("ip -brief addr").get("stdout", "")
    elif TARGET_SYSTEM == "PowerShell":
        results["ip_info"] = execute_command("Get-NetIPAddress -AddressFamily IPv4 | Select-Object IPAddress").get("stdout", "")
    else:
        results["ipconfig"] = execute_command("ipconfig").get("stdout", "")[:2000]
    return {{"status": "success", "request_type": "IP Information", "results": results}}

def handle_network_request():
    results = {{}}
    if TARGET_SYSTEM in ["kali-linux windows", "kali-linux", "wsl"]:
        results["interfaces"] = execute_command("ip -brief addr").get("stdout", "")
        results["routing"] = execute_command("ip route").get("stdout", "")
    elif TARGET_SYSTEM == "PowerShell":
        results["adapters"] = execute_command("Get-NetAdapter | Format-Table").get("stdout", "")
    else:
        results["ipconfig_all"] = execute_command("ipconfig /all").get("stdout", "")[:3000]
    return {{"status": "success", "request_type": "Network Information", "results": results}}

def handle_dns_request():
    results = {{}}
    if TARGET_SYSTEM in ["kali-linux windows", "kali-linux", "wsl"]:
        results["resolv_conf"] = execute_command("cat /etc/resolv.conf").get("stdout", "")
    else:
        results["dns_servers"] = execute_command("ipconfig /all | findstr DNS").get("stdout", "")
    return {{"status": "success", "request_type": "DNS Information", "results": results}}

def handle_ping_request():
    results = {{}}
    for target in ["1.1.1.1", "google.com"]:
        if TARGET_SYSTEM in ["kali-linux windows", "kali-linux", "wsl"]:
            result = execute_command(f"ping -c 2 {{target}}")
        else:
            result = execute_command(f"ping {{target}} -n 2")
        results[target] = result.get("stdout", "")[:500]
    return {{"status": "success", "request_type": "Ping Test", "results": results}}

def handle_open_request():
    request_lower = USER_REQUEST.lower()
    if "snapchat" in request_lower:
        return {{
            "status": "info",
            "request_type": "Open Application",
            "message": "Snapchat is a messaging app. You can open it via browser.",
            "command": "start https://web.snapchat.com"
        }}
    elif "chrome" in request_lower:
        return {{
            "status": "executed",
            "request_type": "Open Browser", 
            "command": "start chrome"
        }}
    return handle_general_request()

def handle_general_request():
    return {{
        "status": "received",
        "request_type": "General Request",
        "message": f"Request received: {{USER_REQUEST[:200]}}"
    }}

def save_results(results):
    output_file = f"codex_response_{{datetime.now().strftime('%Y%m%d_%H%M%S')}}.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    return output_file

if __name__ == "__main__":
    print("=" * 50)
    print("CodeX - WiFi Guardian Assistant")
    print("=" * 50)
    print(f"Request: {{USER_REQUEST[:100]}}")
    print(f"System: {{TARGET_SYSTEM}}")
    print("-" * 50)
    
    response = analyze_request()
    print(f"Status: {{response.get('status', 'unknown')}}")
    print(f"Type: {{response.get('request_type', 'unknown')}}")
    
    if 'results' in response:
        for key, value in response['results'].items():
            print(f"  {{key}}: {{value[:200] if value else '(empty)'}}")
    
    if 'command' in response:
        print(f"Command: {{response['command']}}")
    
    output_file = save_results(response)
    print("=" * 50)
    print(f"Results saved to: {{output_file}}")
'''

    return script
