#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CodeX Task Request - Generated by WiFi Guardian Toolkit
   Time: 2026-05-14 23:19:29
   System: kali-linux windows
"""

import os
import sys
import subprocess
import json
import socket
import platform
from datetime import datetime

# ============================================================
# طلب المستخدم الأصلي
# ============================================================
USER_REQUEST = """امر فحص الشبكات"""

# النظام المستهدف
TARGET_SYSTEM = "kali-linux windows"

# معلومات إضافية
REQUEST_INFO = {
    "timestamp": "2026-05-14 23:19:29",
    "requester": "WiFi Guardian Toolkit",
    "request": USER_REQUEST[:200],
    "target_system": TARGET_SYSTEM,
    "hostname": socket.gethostname(),
    "platform": platform.system(),
    "python_version": sys.version
}

# ============================================================
# دوال مساعدة
# ============================================================

def log_message(message, level="INFO"):
    """تسجيل رسالة مع طابع زمني."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] [{level}] {message}")

def execute_command(command, shell=True):
    """تنفيذ أمر نظامي وإرجاع النتيجة."""
    try:
        result = subprocess.run(
            command if isinstance(command, list) else command,
            capture_output=True,
            text=True,
            shell=shell,
            timeout=30
        )
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "Timeout (30s)"}
    except Exception as e:
        return {"success": False, "error": str(e)}

def analyze_request():
    """تحليل طلب المستخدم وتنفيذ الإجراء المناسب."""
    log_message(f"تحليل الطلب: {USER_REQUEST[:100]}...")
    
    # تحليل الكلمات المفتاحية
    request_lower = USER_REQUEST.lower()
    
    # أوامر الشبكة
    if any(word in request_lower for word in ["ip", "عنوان", "address", "اي بي"]):
        return handle_ip_request()
    
    elif any(word in request_lower for word in ["ويفاي", "wifi", "wi-fi", "شبكة", "network"]):
        return handle_network_request()
    
    elif any(word in request_lower for word in ["dns", "دي ان اس", "doh", "dot"]):
        return handle_dns_request()
    
    elif any(word in request_lower for word in ["فحص", "scan", "تحقق", "check"]):
        return handle_scan_request()
    
    elif any(word in request_lower for word in ["ping", "بنق", "اتصال"]):
        return handle_ping_request()
    
    else:
        return handle_general_request()

def handle_ip_request():
    """معالجة طلب معلومات IP."""
    log_message("معالجة طلب IP...")
    results = {}
    
    if TARGET_SYSTEM in ["kali-linux windows", "kali-linux", "wsl"]:
        # أوامر Kali/WSL
        results["hostname_ip"] = execute_command("hostname -I").get("stdout", "").strip()
        results["ip_addr"] = execute_command("ip -brief addr").get("stdout", "")
    elif TARGET_SYSTEM == "PowerShell":
        ip_result = execute_command("Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.IPAddress -notlike '169.254*'} | Select-Object InterfaceAlias,IPAddress")
        results["ip_info"] = ip_result.get("stdout", "")
    else:  # CMD
        results["ipconfig"] = execute_command("ipconfig").get("stdout", "")[:2000]
    
    # إضافة IP المحلي من Python
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        results["local_ip_python"] = s.getsockname()[0]
        s.close()
    except:
        results["local_ip_python"] = "Unable to determine"
    
    return {
        "status": "success",
        "request_type": "IP Information",
        "results": results,
        "suggestion": "يمكنك استخدام هذه المعلومات لفحص اتصال الشبكة."
    }

def handle_network_request():
    """معالجة طلب فحص الشبكة."""
    log_message("معالجة طلب الشبكة...")
    results = {}
    
    if TARGET_SYSTEM in ["kali-linux windows", "kali-linux", "wsl"]:
        results["interfaces"] = execute_command("ip -brief addr").get("stdout", "")
        results["routing"] = execute_command("ip route").get("stdout", "")
        results["arp_table"] = execute_command("arp -a").get("stdout", "")
    elif TARGET_SYSTEM == "PowerShell":
        results["adapters"] = execute_command("Get-NetAdapter | Format-Table -AutoSize").get("stdout", "")
        results["ip_config"] = execute_command("Get-NetIPConfiguration").get("stdout", "")
    else:
        results["ipconfig_all"] = execute_command("ipconfig /all").get("stdout", "")[:3000]
        results["arp"] = execute_command("arp -a").get("stdout", "")
    
    return {
        "status": "success",
        "request_type": "Network Information",
        "results": results,
        "suggestion": "تحقق من وجود أي تكوينات غير متوقعة في الشبكة."
    }

def handle_dns_request():
    """معالجة طلب معلومات DNS."""
    log_message("معالجة طلب DNS...")
    results = {}
    
    if TARGET_SYSTEM in ["kali-linux windows", "kali-linux", "wsl"]:
        results["resolv_conf"] = execute_command("cat /etc/resolv.conf").get("stdout", "")
        results["dns_test"] = execute_command("dig +short cloudflare.com @1.1.1.1").get("stdout", "")
    else:
        results["dns_servers"] = execute_command("ipconfig /all | findstr DNS").get("stdout", "")
        results["nslookup"] = execute_command("nslookup google.com 1.1.1.1").get("stdout", "")
    
    return {
        "status": "success",
        "request_type": "DNS Information",
        "results": results,
        "suggestion": "تأكد من أن DNS يعمل بشكل صحيح."
    }

def handle_ping_request():
    """معالجة طلب Ping."""
    log_message("معالجة طلب Ping...")
    results = {}
    
    targets = ["1.1.1.1", "google.com"]
    for target in targets:
        if TARGET_SYSTEM in ["kali-linux windows", "kali-linux", "wsl"]:
            result = execute_command(f"ping -c 2 {target}")
        else:
            result = execute_command(f"ping {target} -n 2")
        results[target] = result.get("stdout", "")[:500]
    
    return {
        "status": "success",
        "request_type": "Ping Test",
        "results": results,
        "suggestion": "إذا فشل Ping، تحقق من اتصال الإنترنت."
    }

def handle_scan_request():
    """معالجة طلب فحص."""
    log_message("معالجة طلب الفحص...")
    return {
        "status": "pending",
        "request_type": "Scan Request",
        "message": "سيتم إجراء فحص سريع للشبكة المحلية...",
        "suggestion": "استخدم أوامر محددة للفحص المتقدم مثل nmap (بحذر)."
    }

def handle_general_request():
    """معالجة الطلبات العامة."""
    return {
        "status": "received",
        "request_type": "General Request",
        "message": f"تم استلام طلبك: {USER_REQUEST[:200]}",
        "suggestion": "يرجى توضيح الطلب بشكل أكثر تحديداً (مثال: 'أريد فحص الشبكة' أو 'أعطني عنوان IP')"
    }

def save_results(results):
    """حفظ النتائج في ملف JSON."""
    output_file = f"codex_response_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    log_message(f"تم حفظ النتائج في: {output_file}")
    return output_file

# ============================================================
# التنفيذ الرئيسي
# ============================================================

if __name__ == "__main__":
    print("=" * 60)
    print("🤖 CodeX - WiFi Guardian Toolkit Assistant")
    print("=" * 60)
    print(f"📝 الطلب المستلم: {USER_REQUEST[:100]}...")
    print(f"🎯 النظام المستهدف: {TARGET_SYSTEM}")
    print(f"💻 الجهاز: {REQUEST_INFO['hostname']}")
    print("-" * 60)
    
    # تنفيذ التحليل
    response = analyze_request()
    
    # عرض النتائج
    print(f"✅ الحالة: {response.get('status', 'unknown')}")
    print(f"📊 نوع الطلب: {response.get('request_type', 'unknown')}")
    
    if 'results' in response:
        print("\n📡 النتائج:")
        for key, value in response['results'].items():
            preview = value[:300] if value else '(فارغ)'
            print(f"   {key}: {preview}")
    
    if 'message' in response:
        print(f"\n💬 رسالة: {response['message']}")
    
    if 'suggestion' in response:
        print(f"\n💡 اقتراح: {response['suggestion']}")
    
    # حفظ النتائج
    output_file = save_results(response)
    print("\n" + "=" * 60)
    print(f"✅ تم إكمال المعالجة - النتائج محفوظة في {output_file}")
    print("=" * 60)
